import Head from "next/head";
import React, { PropsWithChildren } from "react";

export const ContentLayout: React.FC<PropsWithChildren> = ({ children }: PropsWithChildren) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-green-400">{children}</main>
    </>
  );
};
